name: Build and Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    environment: Development

    services:

      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest

        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: TestSqlServer@2026#Xunit

        ports:
          - 1433:1433

        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd
          -S localhost
          -U sa
          -P 'TestSqlServer@2026#Xunit'
          -C
          -Q 'SELECT 1'
          || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 30

    steps:

      # ==========================================
      # Checkout
      # ==========================================

      - name: Checkout
        uses: actions/checkout@v4


      # ==========================================
      # Setup .NET
      # ==========================================

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'


      # ==========================================
      # Install EF CLI
      # ==========================================

      - name: Install EF CLI
        run: dotnet tool install --global dotnet-ef --version 8.*


      # ==========================================
      # Restore
      # ==========================================

      - name: Restore
        run: dotnet restore


      # ==========================================
      # Build Product Web Tests
      # ==========================================

      - name: Build Product Web Tests
        run: >
          dotnet build
          testing.product.web.tests/testing.product.web.tests.csproj
          --no-restore


      # ==========================================
      # Run EF Migrations
      # ==========================================

      - name: Run migrations
        run: >
          dotnet ef database update
          --project testing-web/testing-web.csproj
          --startup-project testing-api/testing-api.csproj
          -- --environment Development


      # ==========================================
      # Run Product Web Tests ONLY
      # ==========================================

      - name: Run Product Web Tests
        env:
          TEST_CONNECTION_STRING: >-
            Server=localhost,1433;
            Database=TestingProductWebDb_Test;
            User Id=sa;
            Password=TestSqlServer@2026#Xunit;
            TrustServerCertificate=True;

        run: >
          dotnet test
          testing.product.web.tests/testing.product.web.tests.csproj
          --no-build
          --verbosity normal